workdir: "/my/work/dir/databases/"
threads: 8
repeat: 1

# A file in the "envs" with the dependencies to be installed has to match the tool name-version.
# Example: envs/toolA-1.6.0.yaml  and envs/toolB-latest.yaml have to exist
# If a path is given, the pipeline will try to find the executable necessary on that path but will still install the dependencies
tools: 
  toolA:
    "1.6.0": "/path/to/toolA/"
  toolB:
    "latest": ""

dbs:
  "database1":
    folder: "/where/is/the/db1/"
    extension: ".fna.gz"
    taxonomy: "ncbi"
    taxonomy_files: "/misc/files/taxdump.tar.gz"
    assembly_summary: "/files/assembly_summary.txt"
  "database99":
    folder: "/where/is/the/db99/"
    extension: ".fna.gz"
    taxonomy: "ncbi"
    taxonomy_files: "/misc/files/taxdump.tar.gz"
    assembly_summary: "/files/assembly_summary.txt"

run:
   toolA:
     "1.6.0":
       database1:
         fixed_args:
           "--path-to-lib": "/path/to/lib"
         args:
           "--normal-numeric-value": 0.1
           "--normal-string-value": "mystring"
           "--boolean": True
           "--integer-ranges": "0, 100, 10"                 # start, end, interval (end point inclusive)
           "--float-ranges": "0, 1, 0.1"                    # start, end, interval (end point inclusive)
           "--list-numeric-values": [0, 1, 10, 12, 15, ""]  # "" disables argument
           "--list-string-values": ["test", "another", ""]  # "" disables argument
           "--list-boolean-values": [True, False]           # False disables argument
       database99:
         fixed_args:
           "--path-to-lib": "/path/to/lib"
         args:                        # Empty will generate "default" output

   toolB:
     "latest":
       database1:
         fixed_args:
         args:
       database99:
         fixed_args:
         args:
