workdir: "/home/mi/pirov/bigdata/data/metabench_data/databases/"
threads: 30
repeat: 1

tools:
  ganon:
    "1.3.0-dev": "/home/mi/pirov/bigdata/code/ganon/"
  kraken2:
    "2.1.2": ""
  bracken:
    "2.7": ""

dbs:
  "abfv_cg_t1a":
    folder: "/home/mi/pirov/bigdata/data/abfv/20221011_cg_t1a/files/"
    extension: ".fna.gz"
    details: "/home/mi/pirov/bigdata/data/abfv/20221011_cg_t1a/seqinfo.txt"
    taxonomy: "ncbi"
    taxonomy_files: "/home/mi/pirov/bigdata/data/abfv/20221011/taxdump.tar.gz"
  "abfv_rs_repgen":
    folder: "/home/mi/pirov/bigdata/data/abfv_rs_repgen/20221101/files/"
    extension: ".fna.gz"
    details: ""
    taxonomy: "ncbi"
    taxonomy_files: "/home/mi/pirov/bigdata/data/abfv_rs_repgen/20221101/taxdump.tar.gz"

run:
  ganon:
    "1.3.0-dev":
      "abfv_cg_t1a":
        fixed_args:
          "--ncbi-file-info": "/home/mi/pirov/bigdata/data/abfv/20221011_cg_t1a/assembly_summary.txt"
          "--ganon-path": "/home/mi/pirov/bigdata/code/ganon/"
        args:
          "--level": "assembly"
          "--kmer-size": 19
          "--window-size": 31
      "abfv_rs_repgen":
        fixed_args:
          "--ncbi-file-info": "/home/mi/pirov/bigdata/data/abfv_rs_repgen/20221101/assembly_summary.txt"
          "--ganon-path": "/home/mi/pirov/bigdata/code/ganon/"
        args:
          "--level": "assembly"
          "--kmer-size": 19
          "--window-size": 31

  kraken2:
    "2.1.2":
      "abfv_cg_t1a":
        fixed_args:
        args:
      "abfv_rs_repgen":
        fixed_args:
        args:
  
  bracken:
    "2.7":
      "abfv_cg_t1a":
        fixed_args:
          "-d": "/home/mi/pirov/bigdata/data/metabench_data/databases/kraken2/2.1.2/abfv_cg_t1a/default"
        args:
      "abfv_rs_repgen":
        fixed_args:
          "-d": "/home/mi/pirov/bigdata/data/metabench_data/databases/kraken2/2.1.2/abfv_rs_repgen/default"
        args:

# run:
#    tool:
#      version:
#        database:
#          fixed_args:
#          args:
