workdir: "/home/pirov/data/metabench_data/databases/"
threads: 8
repeat: 1

tools:
  ganon:
    "1.2.0": ""
  kraken2:
    "2.1.2": ""
  bracken:
    "2.7": ""

dbs:
  "arc_bac_rs_cg_t1s":
    folder: "/home/pirov/data/abfv_rs_cg_t3s/ab_t1s/files/"
    extension: ".fna.gz"
    details: "/home/pirov/data/abfv_rs_cg_t3s/20220915/2022-09-15_14-49-30_sequence_accession.txt"
    taxonomy: "ncbi"
    taxonomy_files: "/home/pirov/data/abfv_rs_cg_t3s/20220915/taxdump.tar.gz"

run:
  ganon:
    "1.2.0":
      "arc_bac_rs_cg_t1s":
        fixed_args:
          "--ncbi-file-info": "/home/pirov/data/abfv_rs_cg_t3s/ab_t1s/assembly_summary.txt"
        args:
          "--level": "species"

  kraken2:
    "2.1.2":
      "arc_bac_rs_cg_t1s":
        fixed_args:
        args:
          "--max-db-size": 26843545600
  
  bracken:
    "2.7":
      "arc_bac_rs_cg_t1s":
        fixed_args:
          "-d": "/home/pirov/code/metabench/databases/kraken2/2.1.2/arc_bac_rs_cg_t1s/default/"
        args:

# run:
#    tool:
#      version:
#        database:
#          fixed_args:
#          args: