workdir: "./databases/"
threads: 8

tools:
  ganon:
    "1.2.0": "/home/pirov/code/ganon/"
  kraken2:
    "2.1.2": ""

dbs:
  "arc_cg_rs":
    folder: "/home/pirov/data/arc_cg_rs/2022-09-05_16-39-33/files/"
    extension: ".fna.gz"
    details: "/home/pirov/data/arc_cg_rs/2022-09-05_16-39-33/2022-09-05_16-39-33_sequence_accession.txt"
    taxonomy: "ncbi"
    taxonomy_files: "../taxdump.tar.gz"

run:
  ganon:
    "1.2.0":
      "arc_cg_rs":
        fixed_args:
          "--ganon-path": "/home/pirov/code/ganon/"
          "--ncbi-file-info": "/home/pirov/data/arc_cg_rs/assembly_summary.txt"
        args:
          "--kmer-size": [19, 22, 3]
          "--window-size": 35

  kraken2:
    "2.1.2":
      "arc_cg_rs":
        fixed_args:
        args:
# run:
#    tool:
#      version:
#        database:
#          fixed_args:
#          args: