workdir: "/home/pirov/data/metabench_data/results/"
threads: 8
repeat: 1

tools:
  ganon:
    "1.2.0": ""
    "1.3.0-dev": "/home/pirov/code/ganon/"
  kraken2:
    "2.1.2": ""

samples:
  "mende10.1M":
    fq1: "/home/pirov/data/reads/mende/illumina_10species.1M_0.1.fq.gz"
    fq2: "/home/pirov/data/reads/mende/illumina_10species.1M_0.2.fq.gz"
  "mende100.1M":
    fq1: "/home/pirov/data/reads/mende/illumina_100species.1M_0.1.fq.gz"
    fq2: "/home/pirov/data/reads/mende/illumina_100species.1M_0.2.fq.gz"
  "mende400.1M":
    fq1: "/home/pirov/data/reads/mende/illumina_400species.1M_0.1.fq.gz"
    fq2: "/home/pirov/data/reads/mende/illumina_400species.1M_0.2.fq.gz"

run:
  ganon:
    # "1.2.0":
    #   dbs: 
    #     "arc_bac_rs_cg_t1s": "/home/pirov/data/metabench_data/databases/ganon/1.2.0/arc_bac_rs_cg_t1s/"
    #   fixed_args:
    #   args:
    "1.3.0-dev":
      dbs: 
        "arc_bac_rs_cg_t1s": "/home/pirov/data/metabench_data/databases/ganon/1.3.0-dev/arc_bac_rs_cg_t1s/"
      fixed_args:
        "--ganon-path": "/home/pirov/code/ganon/"
      args:
        "--rel-cutoff": [0.0, 0.3, 0.1]
        "--rel-filter": [0, 0.2, 0.1]
        
  kraken2:
    "2.1.2":
      dbs: 
        "arc_bac_rs_cg_t1s": "/home/pirov/data/metabench_data/databases/kraken2/2.1.2/arc_bac_rs_cg_t1s/"
      fixed_args:
      args:

ranks_profiling:
  - superkingdom
  - phylum
  - class
  - order
  - family
  - genus
  - species
