workdir: "/my/work/dir/results/"
threads: 8
repeat: 1

tools:
  toolA:
    "1.6.0": "/path/to/toolA/"
  toolB:
    "2.1.2": ""

samples:
  "sample10":
    fq1: "/path/to/reads10.1.fq.gz"
    fq2: "/path/to/reads10.2.fq.gz"
  "sample100":
    fq1: "/path/to/reads100.1.fq.gz"
    fq2: "" # single reads
  "sample1000":
    fq1: "/path/to/reads1000.1.fq.gz"
    fq2: "/path/to/reads1000.2.fq.gz"

run:
  toolA:
    "1.6.0":
      dbs: 
        "database1": "/my/work/dir/databases/toolA/1.6.0/database1/"
        "database99": "/my/work/dir/databases/toolA/1.6.0/database99/"
      fixed_args:
        "--path-to-lib": "/path/to/lib"
      binning_args:
        "--normal-numeric-value": 0.1
        "--normal-string-value": "mystring"
        "--boolean": True
        "--integer-ranges": "0, 100, 10"                 # start, end, interval (end point inclusive)
        "--float-ranges": "0, 1, 0.1"                    # start, end, interval (end point inclusive)
        "--list-numeric-values": [0, 1, 10, 12, 15, ""]  # "" disables argument
        "--list-string-values": ["test", "another", ""]  # "" disables argument
        "--list-boolean-values": [True, False]           # False disables argument
      profiling_args:
        "--another-arg": "xxx"

  toolB:
    "2.1.2":
      dbs: 
        "database1": "/my/work/dir/databases/toolB/2.1.2/database1/"
        "database99": "/my/work/dir/databases/toolB/2.1.2/database99/"
      fixed_args:
      binning_args:
      profiling_args:


ranks_profiling:
  - superkingdom
  - phylum
  - class
  - order
  - family
  - genus
  - species
# - assembly
