workdir: "results/"
threads: 8

samples:
  "mende10.1M":
    "classify": "/home/pirov/data/reads/mende/illumina_10species.1M.binning.bioboxes.gz"
    "profile": "/home/pirov/data/reads/mende/illumina_10species.profile.bioboxes"
  "mende100.1M":
    "classify": "/home/pirov/data/reads/mende/illumina_100species.1M.binning.bioboxes.gz"
    "profile": "/home/pirov/data/reads/mende/illumina_100species.profile.bioboxes"
  "mende400.1M":
    "classify": "/home/pirov/data/reads/mende/illumina_400species.1M.binning.bioboxes.gz"
    "profile": "/home/pirov/data/reads/mende/illumina_400species.profile.bioboxes"

dbs:
  #"arc_cg_rs": "/home/pirov/code/metabench/databases/ganon/1.2.0/arc_cg_rs/--kmer-size=19_--window-size=35/ganon_db.tax"
  "abfv_rs_cg_t3s": "/home/pirov/data/metabench_data/databases/ganon/1.2.0/abfv_rs_cg_t3s/default.tax"

ranks:
  - superkingdom
  - phylum
  - class
  - order
  - family
  - genus
  - species

taxonomy: "ncbi"
taxonomy_files: "/home/pirov/data/abfv_rs_cg_t3s/20220915/taxdump.tar.gz"

threhsold_profile:
  - 0.1
  - 1
  - 5
  - 10
  - 20


